/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'blog-posts': BlogPost;
    'events-posts': EventsPost;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'events-posts': EventsPostsSelect<false> | EventsPostsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'nl') | ('en' | 'nl')[];
  globals: {
    home: Home;
    hero: Hero;
    blog: Blog;
    events: Event;
    navigation: Navigation;
    footer: Footer;
    'privacy-policy': PrivacyPolicy;
    'cookie-policy': CookiePolicy;
    'terms-and-conditions': TermsAndCondition;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'privacy-policy': PrivacyPolicySelect<false> | PrivacyPolicySelect<true>;
    'cookie-policy': CookiePolicySelect<false> | CookiePolicySelect<true>;
    'terms-and-conditions': TermsAndConditionsSelect<false> | TermsAndConditionsSelect<true>;
  };
  locale: 'en' | 'nl';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role?: ('developer' | 'admin') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for the file (for SEO)
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    openGraph?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  blocks?:
    | (CallToActionBlock | HeadingBlock | ScheduleBlock | StoryBlock | TextImageBlock | TextBlock | VisualBlock)[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatisch gegenereerd op basis van de title
   */
  slug?: string | null;
  url: string;
  /**
   * Automatically generated from URL
   */
  urlWithoutLocale?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  image: number | Media;
  showHeading?: boolean | null;
  heading?: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  button: {
    variant: 'primaryButton' | 'whiteButton' | 'darkButton' | 'transparentButton';
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?: ('' | 'home' | 'page' | 'blog' | 'blog-post' | 'events' | 'event-post') | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
  };
  background: 'transparent' | 'white' | 'light';
  paddingTop: 'none' | 'small' | 'medium' | 'large';
  paddingBottom: 'none' | 'small' | 'medium' | 'large';
  applyCustomId?: boolean | null;
  customId?: string | null;
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'call-to-action-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  minRead: number;
  image: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatisch gegenereerd op basis van de title
   */
  slug?: string | null;
  /**
   * Automatically generated from slug
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-posts".
 */
export interface EventsPost {
  id: number;
  title: string;
  image: number | Media;
  date?: string | null;
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  showButton?: boolean | null;
  button?: {
    variant: 'primaryButton' | 'whiteButton' | 'darkButton' | 'transparentButton';
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?: ('' | 'home' | 'page' | 'blog' | 'blog-post' | 'events' | 'event-post') | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatisch gegenereerd op basis van de title
   */
  slug?: string | null;
  /**
   * Automatically generated from slug
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock".
 */
export interface HeadingBlock {
  tagName: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  text: string;
  hlTexts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  centered?: boolean | null;
  background: 'transparent' | 'white' | 'light';
  paddingTop: 'none' | 'small' | 'medium' | 'large';
  paddingBottom: 'none' | 'small' | 'medium' | 'large';
  applyCustomId?: boolean | null;
  customId?: string | null;
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heading-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleBlock".
 */
export interface ScheduleBlock {
  iframeUrl: string;
  background: 'transparent' | 'white' | 'light';
  paddingTop: 'none' | 'small' | 'medium' | 'large';
  paddingBottom: 'none' | 'small' | 'medium' | 'large';
  applyCustomId?: boolean | null;
  customId?: string | null;
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'schedule-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoryBlock".
 */
export interface StoryBlock {
  heading: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  blueTexts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  redTexts?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  pictures?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  quote?: string | null;
  background: 'transparent' | 'white' | 'light';
  paddingTop: 'none' | 'small' | 'medium' | 'large';
  paddingBottom: 'none' | 'small' | 'medium' | 'large';
  applyCustomId?: boolean | null;
  customId?: string | null;
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'story-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlock".
 */
export interface TextImageBlock {
  showHeading?: boolean | null;
  heading?: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  text: {
    text: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  showButton?: boolean | null;
  button?: {
    variant: 'primaryButton' | 'whiteButton' | 'darkButton' | 'transparentButton';
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?: ('' | 'home' | 'page' | 'blog' | 'blog-post' | 'events' | 'event-post') | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
  };
  image: {
    file: number | Media;
    posMo: 'top' | 'bottom';
    posDe: 'left' | 'right';
    fit: 'contain' | 'cover';
    width: number;
    height?: ('small' | 'medium' | 'large') | null;
  };
  background: 'transparent' | 'white' | 'light';
  paddingTop: 'none' | 'small' | 'medium' | 'large';
  paddingBottom: 'none' | 'small' | 'medium' | 'large';
  applyCustomId?: boolean | null;
  customId?: string | null;
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text-image-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  showSubheading?: boolean | null;
  subheading?: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  showHeading?: boolean | null;
  heading?: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  text: {
    text: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  showButton?: boolean | null;
  button?: {
    variant: 'primaryButton' | 'whiteButton' | 'darkButton' | 'transparentButton';
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?: ('' | 'home' | 'page' | 'blog' | 'blog-post' | 'events' | 'event-post') | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
  };
  centered?: boolean | null;
  width: 'small' | 'medium' | 'large';
  background: 'transparent' | 'white' | 'light';
  paddingTop: 'none' | 'small' | 'medium' | 'large';
  paddingBottom: 'none' | 'small' | 'medium' | 'large';
  applyCustomId?: boolean | null;
  customId?: string | null;
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisualBlock".
 */
export interface VisualBlock {
  visual: number | Media;
  showHeading?: boolean | null;
  heading?: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  height: 'small' | 'medium' | 'large';
  applyCustomId?: boolean | null;
  customId?: string | null;
  hidden?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'visual-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  description?: string | null;
  fields?:
    | {
        name?: string | null;
        type?:
          | (
              | ''
              | 'text'
              | 'textarea'
              | 'email'
              | 'tel'
              | 'number'
              | 'select'
              | 'checkbox'
              | 'radio'
              | 'date'
              | 'time'
              | 'datetime-local'
              | 'file'
              | 'url'
              | 'password'
              | 'hidden'
              | 'range'
              | 'color'
              | 'search'
            )
          | null;
        options?:
          | {
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        multiSelect?: boolean | null;
        maxNumFiles?: number | null;
        maxMBs?: number | null;
        includeCheckboxLink?: boolean | null;
        checkboxLink?: {
          textWithLink?: string | null;
          custom?: boolean | null;
          url?: string | null;
          scroll?: boolean | null;
          targetPage?: ('current' | 'home' | 'page') | null;
          urlType?:
            | (
                | ''
                | 'home'
                | 'page'
                | 'blog'
                | 'blog-post'
                | 'events'
                | 'event-post'
                | 'privacy-policy'
                | 'cookie-policy'
                | 'terms-and-conditions'
              )
            | null;
          page?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          blogPost?: {
            relationTo: 'blog-posts';
            value: number | BlogPost;
          } | null;
          eventPost?: {
            relationTo: 'events-posts';
            value: number | EventsPost;
          } | null;
          scrollTarget?: string | null;
          newTab?: boolean | null;
        };
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  uploads?:
    | {
        field: string;
        files: (number | Media)[];
        id?: string | null;
      }[]
    | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'events-posts';
        value: number | EventsPost;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        openGraph?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        'call-to-action-block'?: T | CallToActionBlockSelect<T>;
        'heading-block'?: T | HeadingBlockSelect<T>;
        'schedule-block'?: T | ScheduleBlockSelect<T>;
        'story-block'?: T | StoryBlockSelect<T>;
        'text-image-block'?: T | TextImageBlockSelect<T>;
        'text-block'?: T | TextBlockSelect<T>;
        'visual-block'?: T | VisualBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  slug?: T;
  url?: T;
  urlWithoutLocale?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  image?: T;
  showHeading?: T;
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  text?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
      };
  background?: T;
  paddingTop?: T;
  paddingBottom?: T;
  applyCustomId?: T;
  customId?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeadingBlock_select".
 */
export interface HeadingBlockSelect<T extends boolean = true> {
  tagName?: T;
  text?: T;
  hlTexts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  centered?: T;
  background?: T;
  paddingTop?: T;
  paddingBottom?: T;
  applyCustomId?: T;
  customId?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleBlock_select".
 */
export interface ScheduleBlockSelect<T extends boolean = true> {
  iframeUrl?: T;
  background?: T;
  paddingTop?: T;
  paddingBottom?: T;
  applyCustomId?: T;
  customId?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StoryBlock_select".
 */
export interface StoryBlockSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  text?: T;
  blueTexts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  redTexts?:
    | T
    | {
        text?: T;
        id?: T;
      };
  pictures?:
    | T
    | {
        image?: T;
        id?: T;
      };
  quote?: T;
  background?: T;
  paddingTop?: T;
  paddingBottom?: T;
  applyCustomId?: T;
  customId?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextImageBlock_select".
 */
export interface TextImageBlockSelect<T extends boolean = true> {
  showHeading?: T;
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  text?:
    | T
    | {
        text?: T;
      };
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
      };
  image?:
    | T
    | {
        file?: T;
        posMo?: T;
        posDe?: T;
        fit?: T;
        width?: T;
        height?: T;
      };
  background?: T;
  paddingTop?: T;
  paddingBottom?: T;
  applyCustomId?: T;
  customId?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  showSubheading?: T;
  subheading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  showHeading?: T;
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  text?:
    | T
    | {
        text?: T;
      };
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
      };
  centered?: T;
  width?: T;
  background?: T;
  paddingTop?: T;
  paddingBottom?: T;
  applyCustomId?: T;
  customId?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VisualBlock_select".
 */
export interface VisualBlockSelect<T extends boolean = true> {
  visual?: T;
  showHeading?: T;
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  height?: T;
  applyCustomId?: T;
  customId?: T;
  hidden?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  minRead?: T;
  image?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  slug?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events-posts_select".
 */
export interface EventsPostsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  date?: T;
  summary?: T;
  content?: T;
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  slug?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  fields?:
    | T
    | {
        name?: T;
        type?: T;
        options?:
          | T
          | {
              value?: T;
              id?: T;
            };
        multiSelect?: T;
        maxNumFiles?: T;
        maxMBs?: T;
        includeCheckboxLink?: T;
        checkboxLink?:
          | T
          | {
              textWithLink?: T;
              custom?: T;
              url?: T;
              scroll?: T;
              targetPage?: T;
              urlType?: T;
              page?: T;
              blogPost?: T;
              eventPost?: T;
              scrollTarget?: T;
              newTab?: T;
            };
        required?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?: T;
  uploads?:
    | T
    | {
        field?: T;
        files?: T;
        id?: T;
      };
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  blocks?:
    | (CallToActionBlock | HeadingBlock | ScheduleBlock | StoryBlock | TextImageBlock | TextBlock | VisualBlock)[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  heading: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  paragraph: {
    text: string;
  };
  socialMediaLinks: {
    icon: number | Media;
    url: string;
    id?: string | null;
  }[];
  button: {
    variant: 'primaryButton' | 'whiteButton' | 'darkButton' | 'transparentButton';
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?: ('' | 'page' | 'blog-post' | 'event-post') | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
  };
  showSecondButton?: boolean | null;
  secondButton?: {
    variant: 'primaryButton' | 'whiteButton' | 'darkButton' | 'transparentButton';
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?: ('' | 'page' | 'blog-post' | 'event-post') | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  heading: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  paragraph: {
    text: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  heading: {
    icon?: (number | null) | Media;
    text: string;
    hlTexts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  paragraph: {
    text: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo: number | Media;
  links?:
    | {
        text: string;
        custom?: boolean | null;
        url?: string | null;
        scroll?: boolean | null;
        targetPage?: ('current' | 'home' | 'page') | null;
        urlType?: ('' | 'home' | 'page' | 'blog' | 'blog-post' | 'events' | 'event-post') | null;
        page?: {
          relationTo: 'pages';
          value: number | Page;
        } | null;
        blogPost?: {
          relationTo: 'blog-posts';
          value: number | BlogPost;
        } | null;
        eventPost?: {
          relationTo: 'events-posts';
          value: number | EventsPost;
        } | null;
        scrollTarget?: string | null;
        newTab?: boolean | null;
        dropdown?: boolean | null;
        clickable?: boolean | null;
        sublinks?:
          | {
              text: string;
              custom?: boolean | null;
              url?: string | null;
              scroll?: boolean | null;
              targetPage?: ('current' | 'home' | 'page') | null;
              urlType?: ('' | 'home' | 'page' | 'blog' | 'blog-post' | 'events' | 'event-post') | null;
              page?: {
                relationTo: 'pages';
                value: number | Page;
              } | null;
              blogPost?: {
                relationTo: 'blog-posts';
                value: number | BlogPost;
              } | null;
              eventPost?: {
                relationTo: 'events-posts';
                value: number | EventsPost;
              } | null;
              scrollTarget?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        showOnEveryPage?: boolean | null;
        showOnHomePage?: boolean | null;
        showOnBlogPage?: boolean | null;
        showOnEventsPage?: boolean | null;
        showOnLegalPages?: boolean | null;
        pages?: (number | Page)[] | null;
        id?: string | null;
      }[]
    | null;
  showButton?: boolean | null;
  button?: {
    variant: 'primaryButton' | 'whiteButton' | 'darkButton' | 'transparentButton';
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?: ('' | 'home' | 'page' | 'blog' | 'blog-post' | 'events' | 'event-post') | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
  };
  slideOutMenu?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo: number | Media;
  Paragraph?: string | null;
  email: {
    text: string;
  };
  phone: {
    text: string;
  };
  address: {
    line1: string;
    line2?: string | null;
    line3?: string | null;
    url: string;
  };
  openingHours: {
    text: string;
    id?: string | null;
  }[];
  socialMediaLinks: {
    icon: number | Media;
    url: string;
    id?: string | null;
  }[];
  legalLinks: {
    text: string;
    custom?: boolean | null;
    url?: string | null;
    scroll?: boolean | null;
    targetPage?: ('current' | 'home' | 'page') | null;
    urlType?:
      | (
          | ''
          | 'home'
          | 'page'
          | 'blog'
          | 'blog-post'
          | 'events'
          | 'event-post'
          | 'privacy-policy'
          | 'cookie-policy'
          | 'terms-and-conditions'
        )
      | null;
    page?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    blogPost?: {
      relationTo: 'blog-posts';
      value: number | BlogPost;
    } | null;
    eventPost?: {
      relationTo: 'events-posts';
      value: number | EventsPost;
    } | null;
    scrollTarget?: string | null;
    newTab?: boolean | null;
    id?: string | null;
  }[];
  companyDetails: {
    crn: string;
    vat: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy".
 */
export interface PrivacyPolicy {
  id: number;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy".
 */
export interface CookiePolicy {
  id: number;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions".
 */
export interface TermsAndCondition {
  id: number;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  /**
   * Automatically set
   */
  url?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  blocks?:
    | T
    | {
        'call-to-action-block'?: T | CallToActionBlockSelect<T>;
        'heading-block'?: T | HeadingBlockSelect<T>;
        'schedule-block'?: T | ScheduleBlockSelect<T>;
        'story-block'?: T | StoryBlockSelect<T>;
        'text-image-block'?: T | TextImageBlockSelect<T>;
        'text-block'?: T | TextBlockSelect<T>;
        'visual-block'?: T | VisualBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  paragraph?:
    | T
    | {
        text?: T;
      };
  socialMediaLinks?:
    | T
    | {
        icon?: T;
        url?: T;
        id?: T;
      };
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
      };
  showSecondButton?: T;
  secondButton?:
    | T
    | {
        variant?: T;
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  paragraph?:
    | T
    | {
        text?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  heading?:
    | T
    | {
        icon?: T;
        text?: T;
        hlTexts?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  paragraph?:
    | T
    | {
        text?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
        dropdown?: T;
        clickable?: T;
        sublinks?:
          | T
          | {
              text?: T;
              custom?: T;
              url?: T;
              scroll?: T;
              targetPage?: T;
              urlType?: T;
              page?: T;
              blogPost?: T;
              eventPost?: T;
              scrollTarget?: T;
              newTab?: T;
              id?: T;
            };
        showOnEveryPage?: T;
        showOnHomePage?: T;
        showOnBlogPage?: T;
        showOnEventsPage?: T;
        showOnLegalPages?: T;
        pages?: T;
        id?: T;
      };
  showButton?: T;
  button?:
    | T
    | {
        variant?: T;
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
      };
  slideOutMenu?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  Paragraph?: T;
  email?:
    | T
    | {
        text?: T;
      };
  phone?:
    | T
    | {
        text?: T;
      };
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        line3?: T;
        url?: T;
      };
  openingHours?:
    | T
    | {
        text?: T;
        id?: T;
      };
  socialMediaLinks?:
    | T
    | {
        icon?: T;
        url?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        text?: T;
        custom?: T;
        url?: T;
        scroll?: T;
        targetPage?: T;
        urlType?: T;
        page?: T;
        blogPost?: T;
        eventPost?: T;
        scrollTarget?: T;
        newTab?: T;
        id?: T;
      };
  companyDetails?:
    | T
    | {
        crn?: T;
        vat?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy-policy_select".
 */
export interface PrivacyPolicySelect<T extends boolean = true> {
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cookie-policy_select".
 */
export interface CookiePolicySelect<T extends boolean = true> {
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "terms-and-conditions_select".
 */
export interface TermsAndConditionsSelect<T extends boolean = true> {
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  url?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'blog-posts';
          value: number | BlogPost;
        } | null)
      | ({
          relationTo: 'events-posts';
          value: number | EventsPost;
        } | null);
    global?:
      | (
          | 'home'
          | 'hero'
          | 'blog'
          | 'events'
          | 'navigation'
          | 'footer'
          | 'privacy-policy'
          | 'cookie-policy'
          | 'terms-and-conditions'
        )
      | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}